Target client improvements
gardener/gardener-resource-manager pull request #95
Opened 2020-12-02 19:31 UTC by timebertt

**How to categorize this PR?**

/area scalability robustness quality
/kind enhancement
/priority normal

**What this PR does / why we need it**:

This PR improves the following aspects of the client for the target cluster:
- The cache can be disabled via the newly added command line flag `--target-disable-cache`. In this case, grm won't cache any objects of the target cluster and always talk to the target API server directly (fixes #92).
- Switches to a `DynamicRESTMapper`, which will ensure that resources are rediscovered on `NoMatchErrors`, but discovery calls are not executed more than once every 10 minutes (fixes #93).

I took the chance to refactor the contents of [`app.go`](https://github.com/gardener/gardener-resource-manager/blob/290db4bffb1f1126aa939bc71218098ff4bbd8f8/cmd/gardener-resource-manager/app/app.go#L69), as I found it to be very overloaded and hard to comprehend.
Now
- both the health and secret controller are placed in their own controller package
- controllers and the corresponding options are setup in the respective controller packages in `add.go`
- the health endpoint is moved into its own dedicated package
- the `ClassFilter` logic is moved into its own dedicated package
- all remaining general options (i.e. command line flags) are handled in dedicated files under `cmd`
- `app.go` only instruments those options and `AddToManager` functions to put everything together. This is very similar to how we construct manager, options and controllers in our extensions.

Also, I switched to our gcr copies of the base images.

**Special notes for your reviewer**:

**Release note**:

```feature developer
The cache of the kubernetes client for the target cluster can now be disabled via the `--target-disable-cache` flag.
```
```other operator
gardener-resource-manager now uses a `DynamicRESTMapper`, which will reduce the amount of explicit discovery calls and faster reconciliation loops and some cases.
```

2020-12-03 07:27 UTC, timebertt commented
Also tested this PR in my local gardener setup, shoot creation/reconciliation/hibernation/wakeup/deletion works fine.
Also did some load testing with large secrets like described in #92 and grm was completely stable and at a constant level of `~30MiB` of Memory 💰

2020-12-03 08:00 UTC, timuthy commented
/assign

2020-12-03 17:03 UTC, timuthy requested changes
Nice PR. Now it looks very similar to what we do in the Gardener extension which will further simplify maintenance, thanks for that. I only found one nit for now.

2020-12-04 07:44 UTC, timebertt commented on pkg/cmd/manager.go
> +type ManagerConfig struct {
Sure thing, done :)

2020-12-04 14:32 UTC, timuthy approved these changes
/lgtm

2020-12-04 15:01 UTC, merged